# Site settings
title: TACTIL
email: james@grayxr.com
description: > # this means to ignore newlines until "baseurl:"
  Tactil Exoskeletal Wearable for XR
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tactilxr.com" # the base hostname & protocol for your site
twitter_username: tactilxr
github_username:  grayxr

# Build settings
sass:
  sass_dir: _sass
include: ['_pages']
kramdown:
  input: GFM
